name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main # Запускать workflow при пуше в ветку main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3 # Скачиваем код репозитория

      - name: Setup Node.js # Устанавливаем Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16 # Или ваша версия Node.js

      - name: Install dependencies # Устанавливаем зависимости
        run: npm ci # Или npm install

      - name: Lint
        run: npm run lint  

      - name: Build # Собираем проект
        run: npm run build # Или yarn build, или другая команда сборки

      - name: Deploy to GitHub Pages # Деплоим на GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }} # Токен GitHub
          publish_dir: ./dist # Папка с собранными файлами
          publish_branch: gh-pages # Ветка для публикации